# Ejercicios Clase 2 - Area 3

In [1]:
# Librerias
import numpy as np
import pandas as pd

In [12]:
# Ejercicio 1
arr = np.arange(9, 24)
arr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [13]:
# Ejercicio 2
arr.size

15

In [14]:
# Ejercicio 3
arr2 = np.arange(9, 25).reshape(2, 8)
arr2

array([[ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [68]:
# Ejercicio 4
arr2 = np.arange(9, 25).reshape(4, 4)
arr2

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [69]:
# Ejercicio 5
arr3 = np.array([3,5,6,1,7,9,2,3,6])
print(f"Array con todos los valores: {arr3}")

for elemento in arr3:
    if elemento > 5:
        print("h")

Array con todos los valores: [3 5 6 1 7 9 2 3 6]
h
h
h
h


In [27]:
# Ejercicio 6
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])
div_arr = arr4 / arr5
div_arr

array([0.25, 0.4 , 0.5 ])

In [72]:
# Ejercicio 7
arr4 = np.array([1,2,3])
mul_arr_4 = arr4 * 6
print(f"{arr4} multiplicado por 6 es: {mul_arr_4}")

arr5 = np.array([4,5,6])
mul_arr_5 = arr5 * 6
print(f"{arr5} multiplicado por 6 es: {mul_arr_5}")

[1 2 3] multiplicado por 6 es: [ 6 12 18]
[4 5 6] multiplicado por 6 es: [24 30 36]


In [105]:
# Ejercicio 8
print(f"{mul_arr_4} -> Dimensión: {mul_arr_4.shape}")
print(f"{mul_arr_5} -> Dimensión: {mul_arr_5.shape}")

[ 6 12 18] -> Dimensión: (3,)
[24 30 36] -> Dimensión: (3,)


In [103]:
print(f"{mul_arr_4} -> Tipo de datos: {mul_arr_4.dtype}")
print(f"{mul_arr_5} -> Tipo de datos: {mul_arr_5.dtype}")

[ 6 12 18] -> Tipo de datos: int64
[24 30 36] -> Tipo de datos: int64


In [33]:
# Ejercicio 9
ser1 = pd.Series([4,8,6,2,7,8,2,1,9])
ser1

0    4
1    8
2    6
3    2
4    7
5    8
6    2
7    1
8    9
dtype: int64

In [35]:
# Ejercicio 10
ser2 = pd.Series([4,8,6,2,7,8,2,1,9], index = ["a","b","c","d","e","f","g","h","i"])
ser2

a    4
b    8
c    6
d    2
e    7
f    8
g    2
h    1
i    9
dtype: int64

In [109]:
# Ejercicio 11
valor = ser2.e
print(f"El elemento ubicado en el indice 'e' es: {valor}")

El elemento ubicado en el indice 'e' es: 7


In [40]:
# Ejercicio 12
ser3 = pd.Series([1,5,3,8])
ser4 = pd.Series([4,8,3,9])
div_ser = ser3 % ser4
div_ser

0    1
1    5
2    0
3    8
dtype: int64

In [41]:
# Ejercicio 13
ser5 = pd.Series([1,4,6,8])
mul_ser = ser5 * 4
mul_ser

0     4
1    16
2    24
3    32
dtype: int64

In [63]:
# Ejercicio 14
ser6 = pd.Series([4,8,6,2,7,8,2,1,9])
ser7 = ser6.shift(-1)
ser8 = (ser6 + ser7).dropna()
ser8

0    12.0
1    14.0
2     8.0
3     9.0
4    15.0
5    10.0
6     3.0
7    10.0
dtype: float64

In [110]:
# Ejercicio 14
ser6 = pd.Series([4,8,6,2,7,8,2,1,9])
lista1 = []

for idx, valor in enumerate(ser6):
    a = ser6[idx]
    if idx < len(ser6) - 1:
        b = a + ser6[idx + 1]
        lista1.append(b)

serie_final = pd.Series(lista1)
serie_final

0    12
1    14
2     8
3     9
4    15
5    10
6     3
7    10
dtype: int64

In [158]:
# Ejercicio 15
Mes = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
Ventas = [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630]
Gastos = [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000]
Cobrado = ["S", "N", "N", "S", "S", "N", "S", "S", "S", "N", "S", "N"]
df = pd.DataFrame({"Mes":Mes, "Ventas":Ventas, "Gastos":Gastos, "Cobrado":Cobrado})
df

Mes  Ventas  Gastos Cobrado
0        Enero   10000    6500       S
1      Febrero   15200    6500       N
2        Marzo   14300    6500       N
3        Abril   25800    7850       S
4         Mayo    2560    6500       S
5        Junio   12780    8250       N
6        Julio   32500    6500       S
7       Agosto   23624    9252       S
8   Septiembre   12000    6500       S
9      Octubre   15858   10250       N
10   Noviembre   23250   12450       S
11   Diciembre   11630   13000       N

In [130]:
# Ejercicio 16

# Pregunta 1: ¿Cuántas filas tiene el dataframe?
filas = df.shape[0]
print(f"* El numero de filas del dataframe es: {filas}")

# Pregunta 2: ¿Cuáles son las columnas que los forman?
columnas = df.columns.values
print(f"* Las columnas del dataframe son: {columnas}")

# Pregunta 3: ¿Cuánto espacio ha utilizado en memoria?
espacio = df.memory_usage()
print(f"""* El espacio en memoria usado por cada columna en bytes:
{espacio}
""")

# Pregunta 4: ¿Cuál es la media de las ventas anuales?
ventas = df["Ventas"].mean()
print(f"* La media de las ventas anuales es {round(ventas, 2)}")

# Pregunta 5: Teniendo en cuenta solo las columnas Ventas y Gastos, al final de año, ¿crees que la empresa es rentable?
beneficio = (df["Ventas"] - df["Gastos"]).sum()
print(f"""* Teniendo en cuenta solo esas 2 columnas se podria inferir que si es rentable, ya que las ventas fueron
superiores a los gastos; especificamente se obtuvo unas ganancias anuales de {beneficio}""")

* El numero de filas del dataframe es: 12
* Las columnas del dataframe son: ['Mes' 'Ventas' 'Gastos' 'Cobrado']
* El espacio en memoria usado por cada columna en bytes:
Index      132
Mes         96
Ventas      96
Gastos      96
Cobrado     96
dtype: int64

* La media de las ventas anuales es 16625.17
* Teniendo en cuenta solo esas 2 columnas se podria inferir que si es rentable, ya que las ventas fueron
superiores a los gastos; especificamente se obtuvo unas ganancias anuales de 99450


In [143]:
"""
Ejercicio 17
Información sobre los meses en los que se ha facturado por encima de la facturación media anual.
""" 
df[df["Ventas"] > df["Ventas"].mean()]

Mes  Ventas  Gastos Cobrado
3       Abril   25800    7850       S
6       Julio   32500    6500       S
7      Agosto   23624    9252       S
10  Noviembre   23250   12450       S

In [147]:
"""
Ejercicio 18
Meses en los que hay facturas pendientes de cobro
""" 
df.loc[df["Cobrado"] == "N", "Mes"]

1       Febrero
2         Marzo
5         Junio
9       Octubre
11    Diciembre
Name: Mes, dtype: object

In [148]:
"""
Ejercicio 19
Información sobre los meses en los que los gastos han sido mayores que las ventas.
"""
df[df["Gastos"] > df["Ventas"]]

Mes  Ventas  Gastos Cobrado
4        Mayo    2560    6500       S
11  Diciembre   11630   13000       N

In [159]:
"""
Ejercicio 20
Añade una nueva columna al dataframe que hemos estado utilizando, llamada Beneficio, que tenga sus doce valores
iguales a 0. NOTA: Crea un nuevo dataframe utilizando diccionarios y lo que sabes sobre ellos.
"""
df['Beneficio'] = 0
df2 = df
df2

Mes  Ventas  Gastos Cobrado  Beneficio
0        Enero   10000    6500       S          0
1      Febrero   15200    6500       N          0
2        Marzo   14300    6500       N          0
3        Abril   25800    7850       S          0
4         Mayo    2560    6500       S          0
5        Junio   12780    8250       N          0
6        Julio   32500    6500       S          0
7       Agosto   23624    9252       S          0
8   Septiembre   12000    6500       S          0
9      Octubre   15858   10250       N          0
10   Noviembre   23250   12450       S          0
11   Diciembre   11630   13000       N          0

In [163]:
"""
Ejercicio 21
Añade una nueva columna al dataframe que hemos estado utilizando, llamada Beneficio, que tenga sus doce valores
iguales a 0. NOTA: Crea un nuevo dataframe utilizando diccionarios y lo que sabes sobre ellos.
"""
df2['Beneficio'] = df2["Ventas"] - df2["Gastos"]
df2

Mes  Ventas  Gastos Cobrado  Beneficio
0        Enero   10000    6500       S       3500
1      Febrero   15200    6500       N       8700
2        Marzo   14300    6500       N       7800
3        Abril   25800    7850       S      17950
4         Mayo    2560    6500       S      -3940
5        Junio   12780    8250       N       4530
6        Julio   32500    6500       S      26000
7       Agosto   23624    9252       S      14372
8   Septiembre   12000    6500       S       5500
9      Octubre   15858   10250       N       5608
10   Noviembre   23250   12450       S      10800
11   Diciembre   11630   13000       N      -1370

In [184]:
"""
Ejercicio 22
Meses en los que ha habido pérdidas
"""
df2.loc[df2["Beneficio"] < 0, ["Mes", "Beneficio"]]

Mes  Beneficio
4        Mayo      -3940
11  Diciembre      -1370

In [170]:
"""
Ejercicio 23
Muestra todos los datos sobre el mes en el que hay un mayor beneficio.
"""
df2[df2["Beneficio"] == df2["Beneficio"].max()]

Mes  Ventas  Gastos Cobrado  Beneficio
6  Julio   32500    6500       S      26000

In [181]:
"""
Ejercicio 24
Muestra los meses en los que el beneficio ha sido mayor que la media de los beneficios anuales 
aunque no se hayan cobrado aún todas las facturas.
"""
print(f"La media de los beneficios anuales es {df2['Beneficio'].mean()}")

La media de los beneficios anuales es 8287.5


In [182]:
df2.loc[df2["Beneficio"] > df2["Beneficio"].mean(), ["Mes", "Beneficio"]]

Mes  Beneficio
1     Febrero       8700
3       Abril      17950
6       Julio      26000
7      Agosto      14372
10  Noviembre      10800